let quizStrings = {
"custom": {
    "cnt_select": 2,
    questions: [
        {
            "text": "ma-ta e destepta",
            "A": "adevarat",
            "B": "fals",
            "C": "-",
            "D": "-",
            "correct": "B"
        },
        {
            "text": "ma-ta e sexy",
            "A": "adevarat",
            "B": "fals",
            "C": "-",
            "D": "-",
            "correct": "A"
        },
        {
            "text": "ma-ta e ",
            "A": "blonda",
            "B": "satena",
            "C": "bruneta",
            "D": "vopsita",
            "correct": "D"
        }
    ]
},
"basic": {
    "cnt_select": 10,
    questions: [
        {
            "text": "Nunca llegaron a conocer__________ de su comportamiento.",
            "A": "el por que",
            "B": "el porque",
            "C": "el porqué",
            "D": "-",
            "correct": "C",
        },
        {
            "text": "No había otra posibilidad que callarse _____ tales argumentos.",
            "A": "delante de",
            "B": "ante",
            "C": "antes de",
            "D": "-",
            "correct": "B",
        },
        {
            "text": "Todas las noches sueño _____ viajar al espacio.",
            "A": "con",
            "B": "a",
            "C": "en",
            "D": "-",
            "correct": "A",
        },
        {
            "text": "Este chico estudia casi siete horas ______día.",
            "A": "por",
            "B": "a",
            "C": "al",
            "D": "-",
            "correct": "C",
        },
        {
            "text": "___ alma de este joven está hecha pedazos.",
            "A": "El",
            "B": "La",
            "C": "Un",
            "D": "-",
            "correct": "A",
        },
        {
            "text": "¡A Maribel le encantaría este vestido! ¿______ compramos?",
            "A": "Le lo",
            "B": "Se lo",
            "C": "Se la",
            "D": "-",
            "correct": "B",
        },
        {
            "text": "Me da pena que _____ el tiempo sin hacer nada.",
            "A": "pierdes",
            "B": "pierdas",
            "C": "has perdido",
            "D": "-",
            "correct": "B",
        },
        {
            "text": "Este tío _____siempre aburrido; no sabe divertirse.",
            "A": "es",
            "B": "está",
            "C": "será",
            "D": "-",
            "correct": "B",
        },
        {
            "text": "Cuando _____ me podrás traer un regalo, ¿qué te parece?",
            "A": "vuelvas",
            "B": "vuelves",
            "C": "volverás",
            "D": "-",
            "correct": "A",
        },
        {
            "text": "Sería _____ si pudieras acompañarme al concierto.",
            "A": "más bien",
            "B": "más bueno",
            "C": "major",
            "D": "-",
            "correct": "C",
        },
        {
            "text": "Es evidente que aquí la gente _______muchísimo dinero.",
            "A": "tiene",
            "B": "tenga ",
            "C": "-",
            "D": "-",
            "correct": "A",
        },
        {
            "text": "Me fascina que algunos  jóvenes ________respetuosos con las personas mayores.",
            "A": "sean",
            "B": "son",
            "C": "-",
            "D": "-",
            "correct": "B",
        },
        {
            "text": "Me parece interesante que la ciencia ________cada día nuevos descubrimientos.",
            "A": "descubre",
            "B": "descubra",
            "C": "-",
            "D": "-",
            "correct": "B",
        },
        {
            "text": "Estoy seguro de que su casa __________en el centro de la ciudad.",
            "A": "esté",
            "B": "está",
            "C": "-",
            "D": "-",
            "correct": "B",
        },
        {
            "text": "Te ruego que ________ todos los deberes hoy.",
            "A": "hagas",
            "B": "hace",
            "C": "-",
            "D": "-",
            "correct": "A",
        },
        {
            "text": "Mis padres estarán estáticos  cuando yo ______ un trabajo.",
            "A": "consiga",
            "B": "conseguiré",
            "C": "-",
            "D": "-",
            "correct": "A",
        },
        {
            "text": "Haz tu cama cuando  _______ esta mañana!",
            "A": "te levantarás",
            "B": "te levantes",
            "C": "-",
            "D": "-",
            "correct": "B",
        },
        {
            "text": "No hago nada por la mañana hasta que alguien me ______ mi horóscopo.",
            "A": "leerá",
            "B": "lea",
            "C": "-",
            "D": "-",
            "correct": "B",
        },
        {
            "text": "Aunque ______ mañana nos marcharemos.",
            "A": "llueva",
            "B": "llueve",
            "C": "-",
            "D": "-",
            "correct": "A",
        },
        {
            "text": "Es una lástima que no _______bien el tiempo.",
            "A": "aprovechen",
            "B": "aprovechan",
            "C": "-",
            "D": "-",
            "correct": "A",
        },
        {
            "text": "¿Cuántos viajes emprende Cristóbal Colón?",
            "A": "2",
            "B": "4",
            "C": "6",
            "D": "-",
            "correct": "C",
        },
        {
            "text": "¿A quién propone en primer lugar la idea de preparar un viaje a Las Indias por otra ruta?",
            "A": "a Los Reyes Católicos",
            "B": "al Rey de Portugal",
            "C": "al Rey de Francia",
            "D": "-",
            "correct": "B",
        },
        {
            "text": "¿Cuál era la carabela más grande?",
            "A": "Santa María",
            "B": "La Niña",
            "C": "Pinta",
            "D": "-",
            "correct": "A",
        },
        {
            "text": "¿Qué pretendía Colón?",
            "A": "comerciar con especias",
            "B": "alcanzar la Costa Oriental de Asia por el oeste",
            "C": "descubrir un Nuevo Continente desconocido",
            "D": "-",
            "correct": "B",
        },
        {
            "text": "¿Qué son las Capitulaciones de Santa Fe?",
            "A": "privilegios y condiciones en las que realizaría el viaje",
            "B": "reflexiones de Colón antes de partir",
            "C": "cartas que escribió Colón durante el viaje",
            "D": "-",
            "correct": "A",
        },
        {
            "text": "¿Qué eran los ayllus?",
            "A": "Clanes incas",
            "B": "Clanes mohicanos",
            "C": "Clanes aztecas",
            "D": "-",
            "correct": "A",
        },
        {
            "text": "¿En qué fueron pioneros en medicina los incas?",
            "A": "en dermatología",
            "B": "en practicar la cirugía",
            "C": "en ortodoncia",
            "D": "-",
            "correct": "B",
        },
        {
            "text": "¿Qué es el Machu Picchu?",
            "A": "una ciudad sagrada inca construída a 2.200 metros de altura",
            "B": "un jefe inca",
            "C": "el templo de una ciudad perdida",
            "D": "-",
            "correct": "A",
        },
        {
            "text": "¿Quién inventó el número cero?",
            "A": "los aztecas",
            "B": "los incas",
            "C": "los mayas",
            "D": "-",
            "correct": "C",
        },
        {
            "text": "¿Quiénes eran politeístas?",
            "A": "los mayas y los incas",
            "B": "los aztecas y los incas",
            "C": "los aztecas y los mayas",
            "D": "-",
            "correct": "B",
        },
        {
            "text": "En España predomina:",
            "A": "en el sur y sureste el clima templado oceánico ó templado y en el norte y noroeste el clima mediterráneo",
            "B": "en el norte y noroeste el clima mediterráneo y en el sur y sureste el clima templado oceánico",
            "C": "en el norte y noroeste el  clima templado oceánico húmedo y en  el sur y sureste el clima mediterráneo",
            "D": "-",
            "correct": "C",
        },
        {
            "text": "El clima mediterráneo se caracteriza por:",
            "A": "temperaturas suaves tanto en verano como en invierno",
            "B": "máximo de lluvias en primavera y otoño y un mínimo estival",
            "C": "lluvias escasas y temperaturas extremas",
            "D": "-",
            "correct": "B",
        },
        {
            "text": "Galicia limita:",
            "A": "al norte con el Mar Cantábrico, al sur con el el Océano Atlántico, al este  con Portugal, al oeste Asturias y Castilla-León",
            "B": "al norte con el Océano Atlántico, al sur con Portugal, al este con Asturias y Castilla-León, al oeste con el Mar Cantábrico",
            "C": "al norte con el Mar Cantábrico, al sur con Portugal, al oeste con el Océano Atlántico, al este con Asturias y Castilla-León",
            "D": "-",
            "correct": "C",
        },
        {
            "text": "Andalucía limita:",
            "A": "al norte con Extremadura y Castilla-La Mancha, al sur con el Mar Mediterráneo y el Océano Atlántico, al oeste con Portugal y al este con Murcia",
            "B": "al norte con el Mar Mediterráneo, al sur con el Océano Atlántico, al oeste con Portugal, al este con Murcia",
            "C": "al norte con el Océano Atlántico, al sur con el Mar Mediterráneo, al oeste con Murcia, al este con Portugal",
            "D": "-",
            "correct": "A",
        },
    ]
}
}
