let quizStrings = [
    "Nunca llegaron a conocer__________ de su comportamiento. $ el por que $ el porque $ el porqué $ - $ C",
    "No había otra posibilidad que callarse _____ tales argumentos. $ delante de $ ante $ antes de $ - $ B",
    "Todas las noches sueño _____ viajar al espacio. $ con $ a $ en $ - $ A",
    "Este chico estudia casi siete horas ______día. $ por $ a $ al $ - $ C",
    "___ alma de este joven está hecha pedazos. $ El $ La $ Un $ - $ A",
    "¡A Maribel le encantaría este vestido! ¿______ compramos? $ Le lo $ Se lo $ Se la $ - $ B",
    "Me da pena que _____ el tiempo sin hacer nada. $ pierdes $ pierdas $ has perdido $ - $ B",
    "Este tío _____siempre aburrido; no sabe divertirse. $ es $ está $ será $ - $ B",
    "Cuando _____ me podrás traer un regalo, ¿qué te parece? $ vuelvas $ vuelves $ volverás $ - $ A",
    "Sería _____ si pudieras acompañarme al concierto. $ más bien $ más bueno $ major $ - $ C",
    "Es evidente que aquí la gente _______muchísimo dinero. $ tiene $ tenga $ - $ - $ A",
    "Me fascina que algunos  jóvenes ________respetuosos con las personas mayores. $ sean $ son $ - $ - $ B",
    "Me parece interesante que la ciencia ________cada día nuevos descubrimientos. $ descubre $ descubra $ - $ - $ B",
    "Estoy seguro de que su casa __________en el centro de la ciudad. $ esté $ está $ - $ - $ B",
    "Te ruego que ________ todos los deberes hoy. $ hagas $ hace $ - $ - $ A",
    "Mis padres estarán estáticos  cuando yo ______ un trabajo. $ consiga $ conseguiré $ - $ - $ A",
    "Haz tu cama cuando  _______ esta mañana! $ te levantarás $ te levantes $ - $ - $ B",
    "No hago nada por la mañana hasta que alguien me ______ mi horóscopo. $ leerá $ lea $ - $ - $ B",
    "Aunque ______ mañana nos marcharemos. $ llueva $ llueve $ - $ - $ A",
    "Es una lástima que no _______bien el tiempo. $ aprovechen $ aprovechan $ - $ - $ A",
    "¿Cuántos viajes emprende Cristóbal Colón? $ 2 $ 4 $ 6 $ - $ C",
    "¿A quién propone en primer lugar la idea de preparar un viaje a Las Indias por otra ruta? $ a Los Reyes Católicos $ al Rey de Portugal $ al Rey de Francia $ - $ B",
    "¿Cuál era la carabela más grande? $ Santa María $ La Niña $ Pinta $ - $ A",
    "¿Qué pretendía Colón? $ comerciar con especias $ alcanzar la Costa Oriental de Asia por el oeste $ descubrir un Nuevo Continente desconocido $ - $ B",
    "¿Qué son las Capitulaciones de Santa Fe? $ privilegios y condiciones en las que realizaría el viaje $ reflexiones de Colón antes de partir $ cartas que escribió Colón durante el viaje $ - $ A",
    "¿Qué eran los ayllus? $ Clanes incas $ Clanes mohicanos $ Clanes aztecas $ - $ A",
    "¿En qué fueron pioneros en medicina los incas? $ en dermatología $ en practicar la cirugía $ en ortodoncia $ - $ B",
    "¿Qué es el Machu Picchu? $ una ciudad sagrada inca construída a 2.200 metros de altura $ un jefe inca $ el templo de una ciudad perdida $ - $ A",
    "¿Quién inventó el número cero? $ los aztecas $ los incas $ los mayas $ - $ C",
    "¿Quiénes eran politeístas? $ los mayas y los incas $ los aztecas y los incas $ los aztecas y los mayas $ - $ B",
    "En España predomina: $ en el sur y sureste el clima templado oceánico ó templado y en el norte y noroeste el clima mediterráneo $ en el norte y noroeste el clima mediterráneo y en el sur y sureste el clima templado oceánico $ en el norte y noroeste el  clima templado oceánico húmedo y en  el sur y sureste el clima mediterráneo $ - $ C",
    "El 45% del área de España está dominada por: $ altas cordilleras $ una gran meseta central $ costas $ - $ C",
    "El clima mediterráneo se caracteriza por: $ temperaturas suaves tanto en verano como en invierno $ máximo de lluvias en primavera y otoño y un mínimo estival $ lluvias escasas y temperaturas extremas $ - $ B",
    "Galicia limita: $ al norte con el Mar Cantábrico, al sur con el el Océano Atlántico, al este  con Portugal, al oeste Asturias y Castilla-León $ al norte con el Océano Atlántico, al sur con Portugal, al este con Asturias y Castilla-León, al oeste con el Mar Cantábrico $ al norte con el Mar Cantábrico, al sur con Portugal, al oeste con el Océano Atlántico, al este con Asturias y Castilla-León $ - $ C",
    "Andalucía limita: $ al norte con Extremadura y Castilla-La Mancha, al sur con el Mar Mediterráneo y el Océano Atlántico, al oeste con Portugal y al este con Murcia $ al norte con el Mar Mediterráneo, al sur con el Océano Atlántico, al oeste con Portugal, al este con Murcia $ al norte con el Océano Atlántico, al sur con el Mar Mediterráneo, al oeste con Murcia, al este con Portugal $ - $ A"
]